### ISSUE TITLE
Remove kdump_config manifests for OCP 4.15

### ISSUE THREAD

**Issue by Noreen21** [openshift-kni/cnf-features-deploy#1857]
https://issues.redhat.com/browse/OCPBUGS-25259

Based on the updates on this case, removal of these manifests should be back ported for OCP 4.15.z.

https://github.com/openshift-kni/cnf-features-deploy/blob/release-4.15/ztp/source-crs/extra-manifest/05-kdump-config-master.yaml

https://github.com/openshift-kni/cnf-features-deploy/blob/release-4.15/ztp/source-crs/extra-manifest/05-kdump-config-worker.yaml

**Comment by irinamihai** [comment]
Hey, @Noreen21! I have discussed with @kenyis and Borball and have decided to not backport this. I have updated the Jira accordingly. Based on this, I think this issue can be closed. Thank you.

**Comment by Noreen21** [comment]
Thanks for the info, Irina. I will close it out.
