### ISSUE TITLE
Allow out of tree kustomization inheritance

### ISSUE THREAD

**Issue by MarSik** [openshift-kni/cnf-features-deploy#67]
We should allow admins to prepare kustomization override dirs out of the source tree. Having to create custom dirs inside the sources taints the sources and makes it hard to use for example git submodules.

The structure I would like to suport is:

```
/
/- cnf-features-deploy/feature-configs/demo/performance
/- my-cluster/performance
```

FEATURE_CONFIG=$PWD/my-cluster make -C cnf-features-deploy deploy

There are couple of places that need to be fixed for this to work in the hack directory.

**Comment by yuvalk** [comment]
I guess that if someone want to create his own kustomization dir
he'll want to run it him self
oc apply -k <his dir>

where his kustomization.yaml would point to the feature-configs dir he want to override

**Comment by slintes** [comment]
that was my first thought as well, but then he would have to reimplement all our logic we have in our scripts (retry, wait, ....)
I'm wondering if this already works by setting a relative dir in FEATURES_ENVIRONMENT
`FEATURES_ENVIRONMENT=../../my-cluster make -C cnf-features-deploy deploy`
Would have to test it

**Comment by fedepaol** [comment]
It all boils down to the purpouse of this repo. My understanding was that it was intended to be an example of how to do it (taking inspiration from the blueprint pattern presentation, which we may even misunderstood).
We always said that users will have their way to deploy things, as long as it's in a declarative way.

Said that, we can still do that if that helps for other purpouses (demos, for example).

**Comment by MarSik** [comment]
Exactly, this is about the hack scripts that do much more than just apply the manifests. Btw, if relative path works then it is enough I think.

**Comment by slintes** [comment]
relative path works :) (I just changed `oc apply -k` to `oc kustomize` in `/hack/feature-deploy.sh` in order to just print manifests). Note the modified image of the OperatorSource.
```
$ tree my-cnf-override
my-cnf-override
└── performance
    ├── kustomization.yaml
    └── operator_catalogsource_patch.yaml

1 directory, 2 files

$ cat my-cnf-override/performance/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../cnf-features-deploy/feature-configs/e2e-gcp/performance

patchesStrategicMerge:
  - operator_catalogsource_patch.yaml

$ cat my-cnf-override/performance/operator_catalogsource_patch.yaml
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: performance-addon-operator-catalogsource
  namespace: openshift-marketplace
spec:
  image: quay.io/slintes/performance-addon-operator-registry:latest

$ FEATURES_ENVIRONMENT=../../my-cnf-override FEATURES=performance make -C cnf-features-deploy feature-deploy
make: Entering directory '/home/msluiter/dev/work/cnf/cnf-features-deploy'
FEATURES_ENVIRONMENT=../../my-cnf-override FEATURES="performance" hack/feature-deploy.sh
[INFO]: Pausing
[INFO] Deploying feature 'performance' for environment '../../my-cnf-override'
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-performance-addon
spec: {}
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-performance-addon-operatorgroup
  namespace: openshift-performance-addon
spec:
  targetNamespaces:
  - openshift-performance-addon
---
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: performance-addon-operator-catalogsource
  namespace: openshift-marketplace
spec:
  displayName: Openshift Performance Addon Operator
  icon:
    base64data: ""
    mediatype: ""
  image: quay.io/slintes/performance-addon-operator-registry:latest
  publisher: Red Hat
  sourceType: grpc
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: performance-addon-operator-subscription
  namespace: openshift-performance-addon
spec:
  channel: alpha
  name: performance-addon-operator
  source: performance-addon-operator-catalogsource
  sourceNamespace: openshift-marketplace
---
apiVersion: performance.openshift.io/v1alpha1
kind: PerformanceProfile
metadata:
  name: performance
spec:
  cpu:
    isolated: 1-3
    nonIsolated: "0"
    reserved: 0-1
  hugepages:
    defaultHugepagesSize: 1G
    pages:
    - count: 1
      size: 1G
  nodeSelector:
    node-role.kubernetes.io/worker-cnf: ""
  realTimeKernel:
    enabled: true
[INFO] Deployment successful
make: Leaving directory '/home/msluiter/dev/work/cnf/cnf-features-deploy
```

**Comment by MarSik** [comment]
Cool, I will try using that.

**Comment by slintes** [comment]
@MarSik can we close this? I understand the approach above worked?

**Comment by MarSik** [comment]
Yep.
