### ISSUE TITLE
Need to document requirement of mercurial

### ISSUE THREAD

**Issue by cwilkers** [openshift-kni/cnf-features-deploy#87]
I just had a make fail (with FEATURE_ENVIRONMENT=demo) because hg was not found on my node for building `goautoneg` as follows:

    go: bitbucket.org/ww/goautoneg@v0.0.0-20120707110453-75cd24fc2f2c: hg clone -U https://bitbucket.org/ww/goautoneg . in /home/cwilkers/go/pkg/mod/cache/vcs/59c2185b80ea440a7c3b8c5eff3d8abb68c53dea1f20f615370c924c4150b27f: exec: "hg": executable file not found in $PATH

It is worth either recommending that as a prerequisite or attempting to install (but perhaps not, as we don't already require sudo).

**Comment by slintes** [comment]
I don't have hg on my machine, and we don't have it in our CI docker image.
But I have an idea what is happening: since Go 1.13 dependencies are downloaded from a Go proxy by default, which uses HTTP IIRC. In earlier version dependencies were cloned from the source repo, using git or hg.
So, can it be that you are using Go < 1.13 (please update), or configured Go to not use the proxy?

**Comment by cwilkers** [comment]
@slintes Good questions... I'm running go 1.13.8, however it looks like the dep version I have sitting around was compiled under go 1.12:

```
$  go/bin/dep version
dep:
 version     : v0.5.4
 build date  : 2019-07-01
 git hash    : 1f7c19e
 go version  : go1.12.6
 go compiler : gc
 platform    : linux/amd64
 features    : ImportDuringSolve=false
```

I think in this case since you cannot duplicate, and we found a good culprit, I'll close the issue.

**Comment by fedepaol** [comment]
> I don't have hg on my machine, and we don't have it in our CI docker image.
> But I have an idea what is happening: since Go 1.13 dependencies are downloaded from a Go proxy by default, which uses HTTP IIRC. In earlier version dependencies were cloned from the source repo, using git or hg.
> So, can it be that you are using Go < 1.13 (please update), or configured Go to not use the proxy?

The go download protocol relies on http. However, you must have a proxy set. The difference could be that with some distributions of Go (the one that comes with Fedora, for example) do not have the go u/s proxy set by default.
There were some "privacy" concerns about that, as the way Go works in that regard is that it tries to hit the proxy and then, in case of a failure, it goes to the svc (being it hg or git), so it was exposing private repo names.
